### PR TITLE
Split overall api stats into 2 widgets

### PR DESCRIPTION
**Pull request by ruwiniwj**
## Purpose
Split overall API stats widget into 2 widgets as api ratings and api availability.

Screen Shot 2019-11-14 at 2 08 44 PM

### CODE REVIEW

**Comment by TanyaM** [comment]
Shouldn't we change the dashboard json files along with PR? Since we have changed the name of Overall api stats widget, dashboard json will have non-existence widget names in it which will cause issues.

**Comment by ruwiniwj** [comment]
> Shouldn't we change the dashboard json files along with PR? Since we have changed the name of Overall api stats widget, dashboard json will have non-existence widget names in it which will cause issues.

Fixed

**Comment by ruwiniwj** [comment]
Fixes https://github.com/wso2/analytics-apim/issues/782
Fixes https://github.com/wso2/analytics-apim/issues/779

**Comment by ruwiniwj** [comment]
Fixes https://github.com/wso2/analytics-apim/issues/780

**Pull request merged**
